export const productos = [
    {
        id: 1,
        nombre: "Mochila Wayuu Grande",
        categoria: "mochilas",
        precio: 150000,
        stock: 1,
        imagen: "https://d2d21jw8en5l3a.cloudfront.net/vendty2_db_28302_luis2020/imagenes_productos/MOCHILA%20WAYUU%20DISE%C3%91O%2011%201.png",
        descripcion: "Mochila Wayuu tejida a mano con diseños únicos.",
        descripcionDetallada: "Cada mochila es tejida artesanalmente por las comunidades Wayuu. Ideal para uso diario o como regalo especial.",
        origen: "La Guajira, Colombia",
        tecnica: "Tejido artesanal",
    },
    {
        id: 2,
        nombre: "Ruana Artesanal",
        categoria: "ruanas",
        precio: 200000,
        stock: 5,
        imagen: "https://www.giiveaway.com/cdn/shop/files/Ruana_Ruana_Hombre_Rayas_Artesanal_Capota_Piramides_Doble_Faz_para_Hombre_Negro_Camel_Giive_-_OMA782-1_2.webp?v=1731475964&width=416",
        descripcion: "Ruana artesanal tejida con lana de alta calidad.",
        descripcionDetallada: "Esta ruana está hecha con lana natural, perfecta para días fríos. Combina tradición y estilo.",
        origen: "Boyacá, Colombia",
        tecnica: "Tejido en telar",
    },
    {
        id: 3,
        nombre: "Mochila Wayuu Mediana",
        categoria: "mochilas",
        precio: 120000,
        stock: 20,
        imagen: "https://www.aguasaladahandmade.com/pics/productos/36816334102148419707505041623444114005557248n.jpg",
        descripcion: "Mochila mediana tejida a mano con patrones coloridos.",
        descripcionDetallada: "Con diseños exclusivos de la comunidad Wayuu, esta mochila combina funcionalidad y estilo.",
        origen: "La Guajira, Colombia",
        tecnica: "Tejido artesanal",
    },
    {
        id: 4,
        nombre: "Bufanda Tejida",
        categoria: "accesorios",
        precio: 50000,
        stock: 20,
        imagen: "https://pbs.twimg.com/profile_images/677906892732018690/Ly0nGNq0_400x400.jpg",
        descripcion: "Bufanda de lana tejida a mano con diseño único.",
        descripcionDetallada: "Suave y cálida, ideal para complementar tu outfit en invierno.",
        origen: "Nariño, Colombia",
        tecnica: "Tejido a crochet",
    }
];